name: Publish to npm

on:
  push:
    branches:
      - main  # Set the branch you want to trigger the action (usually main or master)

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # Specify your Node.js version
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm install

    - name: Build the package
      run: npm run build  # If you have a build step, otherwise you can skip this

    - name: Bump version and publish to npm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        npm version patch  # You can also use minor or major depending on your versioning strategy
        npm publish
